-- =========================================================
-- Zenzero Hotel — Phase 2: Seed Test User
-- Date: 2026-08-18
-- =========================================================
-- Note: This file is for documentation. Supabase Auth users
-- must be created via the Auth API or dashboard, not via SQL.
--
-- To create a test user, run this in your terminal:
--   curl -X POST https://<project-ref>.supabase.co/auth/v1/admin/users \
--     -H "Authorization: Bearer <service-role-key>" \
--     -H "apikey: <service-role-key>" \
--     -H "Content-Type: application/json" \
--     -d '{
--       "email": "test@zenzero.com",
--       "password": "TestPass123!",
--       "email_confirm": true,
--       "user_metadata": {
--         "full_name": "คุณสมชาย ใจดี",
--         "phone": "081-234-5678"
--       }
--     }'
--
-- The trigger will auto-create a profile row with full_name + phone.
