/**
 * Supabase implementation of the Account (User profile) data layer.
 *
 * Used by `app/actions/account.ts` for the /account/profile page.
 * Reads/writes the user's own row in `public.profiles` via the
 * session client — RLS enforces owner-only access on SELECT/UPDATE.
 *
 * Server-side R2 upload (`uploadOwnAvatar`) lives in a separate path
 * because R2 writes need the admin client (service role bypasses RLS
 * for the bucket put).
 *
 * Phase 36 — added admin-only customer management functions
 * (listCustomers / getCustomerById / suspendCustomer / unsuspendCustomer).
 * These use `createAdminClient()` to bypass RLS — the server actions
 * in `app/actions/admin/customers.ts` enforce the admin-only role gate.
 */
import { createClient } from '@/lib/supabase/server'
import { wrapSupabaseError } from '@/lib/errors/supabase'
import { createAdminClient } from '@/lib/supabase/admin'
import type { AccountProfile, Customer, LinkedIdentity, IdentityLinkSafety } from './types'

export async function getOwnProfile(): Promise<AccountProfile | null> {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return null

  const { data, error } = await supabase
    .from('profiles')
    .select('id, full_name, phone, birthdate, avatar_key, email, created_at, role, is_active, locale')
    .eq('id', user.id)
    .maybeSingle()
  if (error) wrapSupabaseError('getOwnProfile', error)
  return (data as AccountProfile | null) ?? null
}

export async function updateOwnProfile(
  args: {
    fullName?: string
    phone?: string | null
    birthdate?: string | null
  },
): Promise<void> {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) throw new Error('Not authenticated')

  // Supabase `.update()` ignores undefined keys — caller controls which
  // fields are touched. Used for staff (phone-only) vs User (full) paths.
  const { error } = await supabase
    .from('profiles')
    .update(args)
    .eq('id', user.id)
  if (error) wrapSupabaseError('updateOwnProfile', error)
}

/**
 * Soft-delete: flip is_active=false. User can't sign back in but
 * bookings + reviews remain intact (matches `setStaffActive` semantics
 * from admin/staff.ts).
 */
export async function deactivateOwnAccount(): Promise<void> {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) throw new Error('Not authenticated')

  const { error } = await supabase
    .from('profiles')
    .update({ is_active: false })
    .eq('id', user.id)
  if (error) wrapSupabaseError('deactivateOwnAccount', error)
}

/**
 * Update avatar_key in the user's profile. Called after the server-side
 * R2 upload in `uploadAvatarAction`.
 */
export async function uploadOwnAvatar(avatarKey: string): Promise<void> {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) throw new Error('Not authenticated')

  const { error } = await supabase
    .from('profiles')
    .update({ avatar_key: avatarKey })
    .eq('id', user.id)
  if (error) wrapSupabaseError('uploadOwnAvatar', error)
}

/**
 * Get the user's email from their auth session (not stored on profiles).
 * Used by `changePasswordAction` to verify current password.
 */
export async function getOwnEmail(): Promise<string | null> {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  return user?.email ?? null
}

/**
 * Server-side R2 avatar upload. The avatar_key is generated by the
 * caller (random UUID prevents collision). Uses the admin client to
 * bypass RLS for the bucket put.
 */
export async function putAvatarToR2(args: {
  avatarKey: string
  body: ArrayBuffer | Uint8Array
  contentType: string
}): Promise<void> {
  const { PutObjectCommand } = await import('@aws-sdk/client-s3')
  const { r2Client, R2_BUCKET } = await import('@/lib/r2/client')

  if (!r2Client) {
    throw new Error('R2 not configured (set R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY in .env.local)')
  }

  // AWS SDK v3's PutObject `Body` only accepts Uint8Array (or string /
  // stream). Normalize ArrayBuffer → Uint8Array to satisfy the type.
  const body =
    args.body instanceof Uint8Array ? args.body : new Uint8Array(args.body)

  await r2Client.send(
    new PutObjectCommand({
      Bucket: R2_BUCKET,
      Key: args.avatarKey,
      Body: body,
      ContentType: args.contentType,
      CacheControl: 'public, max-age=31536000, immutable',
    }),
  )
}

// =========================================================
// Phase 37 — Identity linking (multi-provider sign-in)
// =========================================================

/**
 * List all auth identities linked to the currently signed-in user.
 * Used by the LinkedAccountsCard UI to decide which providers are
 * already connected + which can be unlinked (must keep ≥1).
 */
export async function listMyIdentities(): Promise<LinkedIdentity[]> {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return []

  // getUserIdentities() returns ALL identities in one query (no
  // pagination). On user accounts this is always a small set
  // (≤ 5 providers in practice).
  const { data, error } = await supabase.auth.getUserIdentities()
  if (error) {
    // getUserIdentities returns AuthError on network issues; wrap so
    // caller can render a localized "couldn't load" message.
    wrapSupabaseError('listMyIdentities', error)
  }

  const list: LinkedIdentity[] = (data?.identities ?? []).map((id) => {
    const data = (id.identity_data ?? {}) as Record<string, unknown>
    const email =
      typeof data['email'] === 'string' ? (data['email'] as string) : null
    const emailVerified =
      data['email_verified'] === true ||
      // Some providers (legacy configurations) put a string in here.
      String(data['email_verified']) === 'true'
    return {
      identityId: id.identity_id,
      userId: id.user_id,
      provider: id.provider,
      email,
      emailVerified,
      lastSignInAt: id.last_sign_in_at ?? null,
      createdAt: id.created_at ?? null,
    }
  })
  return list
}

/**
 * Helper for ChangePasswordForm / SetPasswordForm branching.
 * True iff the user has at least one 'email'-provider identity
 * (Google-only users → false).
 */
export async function hasPasswordIdentity(): Promise<boolean> {
  const identities = await listMyIdentities()
  return identities.some((i) => i.provider === 'email')
}

/**
 * Defense-in-depth gate before initiating any identity link flow.
 * Calls the can_link_identity_by_email() SECURITY DEFINER function
 * to check that BOTH sides' email is verified.
 *
 * The server action that calls this should pass
 * `newEmailVerified = identity_data.email_verified` from the
 * candidate IdP. This is a defense-in-depth check — Supabase's
 * own gate (the Dashboard "Manual Linking" toggle + the matching
 * Supabase auth code path) is the primary wall.
 */
export async function checkIdentityLinkSafety(args: {
  existingEmail: string
  newEmailVerified: boolean
}): Promise<IdentityLinkSafety> {
  const supabase = await createClient()
  const { data, error } = await supabase.rpc('can_link_identity_by_email', {
    p_existing_email: args.existingEmail,
    p_new_email_verified: args.newEmailVerified,
  })
  if (error) wrapSupabaseError('checkIdentityLinkSafety', error)
  const row = (data as Array<Record<string, unknown>> | null)?.[0]
  if (!row) {
    // Defensive — RPC always returns a row, but if it doesn't, refuse.
    return {
      safeToLink: false,
      existingUserId: null,
      existingEmailVerified: false,
      reason: 'email_mismatch',
    }
  }
  return {
    safeToLink: row['safe_to_link'] === true,
    existingUserId: (row['existing_user_id'] as string | null) ?? null,
    existingEmailVerified: row['existing_email_verified'] === true,
    reason: row['reason'] as IdentityLinkSafety['reason'],
  }
}

/**
 * Initiate Google OAuth as an identity-linking flow for the
 * currently signed-in user. Calls supabase.auth.linkIdentity()
 * (different from signInWithOAuth — linkIdentity requires a session
 * and attaches a new identity to the existing user).
 *
 * Returns the provider URL — caller (server action) calls
 * `redirect(url)` to navigate the browser to Google consent.
 *
 * IMPORTANT: `skipBrowserRedirect: true` is required server-side,
 * otherwise the SDK would call window.location.assign() which is
 * undefined in Node and throws.
 */
export async function getGoogleLinkUrl(args: {
  origin: string
  next: string
}): Promise<string | null> {
  const supabase = await createClient()
  const {
    data: { session },
  } = await supabase.auth.getSession()
  if (!session) return null

  const { data, error } = await supabase.auth.linkIdentity({
    provider: 'google',
    options: {
      redirectTo: `${args.origin}/auth/callback?intent=link&next=${encodeURIComponent(args.next)}`,
      queryParams: { prompt: 'select_account' },
      skipBrowserRedirect: true,
    },
  })

  if (error) wrapSupabaseError('getGoogleLinkUrl', error)
  return data?.url ?? null
}

/**
 * Set a password for a user who currently has no email/password
 * identity (e.g. signed up via Google).
 *
 * Uses the service-role client to bypass RLS — this is server-only
 * and the user's session has already been verified by requireRole()
 * in the calling server action. The service-role direct password set
 * is the canonical way to attach a credential without knowing the
 * old one (Supabase does NOT require a recent login for admin-set
 * passwords because the admin client is already privileged).
 *
 * Errors propagate as caught PostgRESTError; the caller wraps
 * with actionFail() for UI display.
 */
export async function setPasswordViaAdmin(args: {
  userId: string
  newPassword: string
}): Promise<void> {
  const admin = await createAdminClient()
  const { error } = await admin.auth.admin.updateUserById(args.userId, {
    password: args.newPassword,
  })
  if (error) wrapSupabaseError('setPasswordViaAdmin', error)
}

/**
 * Unlink an identity from the current user.
 *
 * Refuses if removing this identity would leave the user with
 * zero identities (would lock them out). Supabase also enforces
 * this on the server (returns 422), but the pre-check makes
 * the error message clearer.
 *
 * Requires the user to be signed in (the auth.uid() / session
 * context is what linkIdentity / unlinkIdentity bind against).
 */
export async function unlinkIdentityById(identityId: string): Promise<void> {
  const supabase = await createClient()
  // Pre-check via the LinkedIdentity DTO (cheaper to compute) — how many
  // identities would remain if we removed this one?
  const identities = await listMyIdentities()
  const remaining = identities.filter((i) => i.identityId !== identityId)
  if (remaining.length === 0) {
    throw new Error('CANNOT_UNLINK_LAST_IDENTITY')
  }

  // unlinkIdentity needs the RAW UserIdentity shape (id, user_id,
  // identity_id, identity_data, provider, ...). Re-fetch from auth-js so
  // the DTO conversion above doesn't strip required fields.
  const { data, error: listError } = await supabase.auth.getUserIdentities()
  if (listError) wrapSupabaseError('unlinkIdentityById (list)', listError)
  const target = (data?.identities ?? []).find(
    (i) => i.identity_id === identityId,
  )
  if (!target) {
    throw new Error('IDENTITY_NOT_FOUND')
  }

  const { error } = await supabase.auth.unlinkIdentity(target)
  if (error) wrapSupabaseError('unlinkIdentityById', error)
}

// =========================================================
// Phase 36 — Customer management (admin only)
// =========================================================

export interface ListCustomersOptions {
  /** Substring match against full_name OR email OR phone (≥2 chars recommended). */
  search?: string
  /**
   * Filter by suspension state:
   *   - undefined → all customers (active + suspended)
   *   - true      → only suspended
   *   - false     → only active
   */
  isSuspended?: boolean
  /** Cap on returned rows (default 200 to keep list snappy). */
  limit?: number
}

/**
 * List customers (profiles with role='user') with optional search/filter.
 * Service-role client — admin-only callers enforced at the server action
 * layer (`app/actions/admin/customers.ts`).
 *
 * Booking count is NOT joined here to avoid N+1 fan-out for the rare
 * use case of "list every customer with count". The detail page computes
 * the count separately via `getCustomerBookingCount`.
 */
export async function listCustomers(
  opts: ListCustomersOptions = {},
): Promise<Customer[]> {
  const admin = await createAdminClient()
  let q = admin
    .from('profiles')
    .select(
      'id, full_name, email, phone, created_at, is_active, is_suspended, suspended_at, suspended_reason',
    )
    .eq('role', 'user')
    .order('created_at', { ascending: false })

  if (opts.search && opts.search.trim().length >= 2) {
    // ILIKE on full_name OR email OR phone. Wrap in %...% for contains-match.
    const term = `%${opts.search.trim()}%`
    q = q.or(`full_name.ilike.${term},email.ilike.${term},phone.ilike.${term}`)
  }

  if (opts.isSuspended === true) q = q.eq('is_suspended', true)
  if (opts.isSuspended === false) q = q.eq('is_suspended', false)

  if (opts.limit && opts.limit > 0) q = q.limit(opts.limit)

  const { data, error } = await q
  if (error) wrapSupabaseError('listCustomers', error)
  return (data ?? []) as Customer[]
}

/** Fetch a single customer by id. Service-role. Returns null if not found. */
export async function getCustomerById(id: string): Promise<Customer | null> {
  const admin = await createAdminClient()
  const { data, error } = await admin
    .from('profiles')
    .select(
      'id, full_name, email, phone, created_at, is_active, is_suspended, suspended_at, suspended_reason',
    )
    .eq('id', id)
    .eq('role', 'user')
    .maybeSingle()
  if (error) wrapSupabaseError('getCustomerById', error)
  return (data as Customer | null) ?? null
}

/** Count bookings for one customer. Service-role bypasses booking RLS. */
export async function getCustomerBookingCount(customerId: string): Promise<number> {
  const admin = await createAdminClient()
  const { count, error } = await admin
    .from('bookings')
    .select('id', { count: 'exact', head: true })
    .eq('user_id', customerId)
  if (error) wrapSupabaseError('getCustomerBookingCount', error)
  return count ?? 0
}

/**
 * Suspend a customer. Sets `is_suspended=true`, `suspended_at=now()`,
 * optional `suspended_reason`. Returns the updated row.
 * Caller (server action) must verify admin role + self-protection.
 */
export async function suspendCustomer(args: {
  targetId: string
  reason: string | null
}): Promise<Customer> {
  const admin = await createAdminClient()
  const update: Record<string, unknown> = {
    is_suspended: true,
    suspended_at: new Date().toISOString(),
  }
  if (args.reason !== null) update.suspended_reason = args.reason
  const { data, error } = await admin
    .from('profiles')
    .update(update)
    .eq('id', args.targetId)
    .select(
      'id, full_name, email, phone, created_at, is_active, is_suspended, suspended_at, suspended_reason',
    )
    .single()
  if (error) wrapSupabaseError('suspendCustomer', error)
  return data as Customer
}

/**
 * Unsuspend a customer. Clears `is_suspended`, `suspended_at`,
 * `suspended_reason`. Returns the updated row.
 * Caller (server action) must verify admin role + self-protection.
 */
export async function unsuspendCustomer(args: {
  targetId: string
}): Promise<Customer> {
  const admin = await createAdminClient()
  const { data, error } = await admin
    .from('profiles')
    .update({
      is_suspended: false,
      suspended_at: null,
      suspended_reason: null,
    })
    .eq('id', args.targetId)
    .select(
      'id, full_name, email, phone, created_at, is_active, is_suspended, suspended_at, suspended_reason',
    )
    .single()
  if (error) wrapSupabaseError('unsuspendCustomer', error)
  return data as Customer
}