/**
 * Supabase implementation of the Account (User profile) data layer.
 *
 * Used by `app/actions/account.ts` for the /account/profile page.
 * Reads/writes the user's own row in `public.profiles` via the
 * session client — RLS enforces owner-only access on SELECT/UPDATE.
 *
 * Server-side R2 upload (`uploadOwnAvatar`) lives in a separate path
 * because R2 writes need the admin client (service role bypasses RLS
 * for the bucket put).
 */
import { createClient } from '@/lib/supabase/server'
import { wrapSupabaseError } from '@/lib/errors/supabase'
import type { AccountProfile } from './types'

export async function getOwnProfile(): Promise<AccountProfile | null> {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return null

  const { data, error } = await supabase
    .from('profiles')
    .select('id, full_name, phone, birthdate, avatar_key, email, created_at, role, is_active, locale')
    .eq('id', user.id)
    .maybeSingle()
  if (error) wrapSupabaseError('getOwnProfile', error)
  return (data as AccountProfile | null) ?? null
}

export async function updateOwnProfile(
  args: {
    fullName?: string
    phone?: string | null
    birthdate?: string | null
  },
): Promise<void> {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) throw new Error('Not authenticated')

  // Supabase `.update()` ignores undefined keys — caller controls which
  // fields are touched. Used for staff (phone-only) vs User (full) paths.
  const { error } = await supabase
    .from('profiles')
    .update(args)
    .eq('id', user.id)
  if (error) wrapSupabaseError('updateOwnProfile', error)
}

/**
 * Soft-delete: flip is_active=false. User can't sign back in but
 * bookings + reviews remain intact (matches `setStaffActive` semantics
 * from admin/staff.ts).
 */
export async function deactivateOwnAccount(): Promise<void> {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) throw new Error('Not authenticated')

  const { error } = await supabase
    .from('profiles')
    .update({ is_active: false })
    .eq('id', user.id)
  if (error) wrapSupabaseError('deactivateOwnAccount', error)
}

/**
 * Update avatar_key in the user's profile. Called after the server-side
 * R2 upload in `uploadAvatarAction`.
 */
export async function uploadOwnAvatar(avatarKey: string): Promise<void> {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) throw new Error('Not authenticated')

  const { error } = await supabase
    .from('profiles')
    .update({ avatar_key: avatarKey })
    .eq('id', user.id)
  if (error) wrapSupabaseError('uploadOwnAvatar', error)
}

/**
 * Get the user's email from their auth session (not stored on profiles).
 * Used by `changePasswordAction` to verify current password.
 */
export async function getOwnEmail(): Promise<string | null> {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  return user?.email ?? null
}

/**
 * Server-side R2 avatar upload. The avatar_key is generated by the
 * caller (random UUID prevents collision). Uses the admin client to
 * bypass RLS for the bucket put.
 */
export async function putAvatarToR2(args: {
  avatarKey: string
  body: ArrayBuffer | Uint8Array
  contentType: string
}): Promise<void> {
  const { PutObjectCommand } = await import('@aws-sdk/client-s3')
  const { r2Client, R2_BUCKET } = await import('@/lib/r2/client')

  if (!r2Client) {
    throw new Error('R2 not configured (set R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY in .env.local)')
  }

  // AWS SDK v3's PutObject `Body` only accepts Uint8Array (or string /
  // stream). Normalize ArrayBuffer → Uint8Array to satisfy the type.
  const body =
    args.body instanceof Uint8Array ? args.body : new Uint8Array(args.body)

  await r2Client.send(
    new PutObjectCommand({
      Bucket: R2_BUCKET,
      Key: args.avatarKey,
      Body: body,
      ContentType: args.contentType,
      CacheControl: 'public, max-age=31536000, immutable',
    }),
  )
}